spring:
  data:
    mongodb:
      uri: ${MONGO_DB_URL}
server:
  port: 8133

logging:
  file:
    name: logs/initialtest.log
    path: initialtest
  level:
    com.geppetto: info
  pattern:
    dateformat: "dd-MM-yyyy hh:mm:ss aa"



























